# 此工作流将安装 Python 依赖项，使用多种 Python 版本运行测试并进行代码检查
# 有关更多信息，请参阅：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

名称: Python软件包

触发:
  push:
分支: [ "main" ]
  pull_request:
分支: [ "main" ]

作业:
 构建:

    运行环境: ubuntu-latest
    策略:
      遇到错误即停止: false
    矩阵:
Python版本: ["3.9", "3.10", "3.11"]

    步骤:
    - 使用: actions/checkout@v4
    - : 设置 Python ${ matrix.python-version }}
      使用: actions/setup-python@v3
      with:
        Python 版本: ${{ matrix.python-version }}
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        如果存在 requirements.txt 文件，则执行 pip install -r requirements.txt；
    - name: 使用flake8进行代码检查
      run: |
        # 如果存在 Python 语法错误或未定义的名称，则停止构建
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero 将所有错误视为警告。GitHub 编辑器的宽度为 127 个字符
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - 名称: 使用 pytest 进行测试
      run: |
        pytest
